# accounts/choices.py

PHONE_NUMBER_COUNTRY_CODE_CHOICES = (
	('93', 'Afghanistan'),
	('355', 'Albania'),
	('213', 'Algeria'),
	('1', 'American Samoa'),
	('376', 'Andorra'),
	('244', 'Angola'),
	('1', 'Anguilla'),
	('1', 'Antigua & Barbuda'),
	('54', 'Argentina'),
	('374', 'Armenia'),
	('297', 'Aruba'),
	('61', 'Australia'),
	('43', 'Austria'),
	('994', 'Azerbaijan'),
	('1', 'Bahamas'),
	('973', 'Bahrain'),
	('880', 'Bangladesh'),
	('1', 'Barbasos'),
	('375', 'Belarus'),
	('32', 'Belgium'),
	('501', 'Belize'),
	('229', 'Benin'),
	('1', 'Bermuda'),
	('975', 'Bhutan'),
	('591', 'Bolivia'),
	('387', 'Bosnia & Herzegovina'),
	('267', 'Botswana'),
	('55', 'Brazil'),
	('1', 'British Virgin Islands'),
	('673', 'Brunei'),
	('359', 'Bulgaria'),
	('226', 'Burkina Faso'),
	('257', 'Burundi'),
	('855', 'Cambodia'),
	('237', 'Cameroon'),
	('1', 'Canada'),
	('238', 'Cape Verde'),
	('599', 'Caribbean Netherlands'),
	('1', 'Cayman Islands'),
	('236', 'Central African Republic'),
	('235', 'Chad'),
	('56', 'Chile'),
	('86', 'China'),
	('57', 'Colombia'),
	('269', 'Comoros'),
	('242', 'Congo - Brazzaville'),
	('243', 'Congo - Kinshasa'),
	('682', 'Cook Islands'),
	('506', 'Costa Rica'),
	('385', 'Croatia'),
	('53', 'Cuba'),
	('599', 'Curaçao'),
	('357', 'Cyprus'),
	('420', 'Czechia'),
	('225', 'Côte d’Ivoire'),
	('45', 'Denmark'),
	('253', 'Djibouti'),
	('1', 'Dominica'),
	('1', 'Dominican Republic'),
	('593', 'Ecuador'),
	('20', 'Egypt'),
	('503', 'El Salvador'),
	('240', 'Equatorial Guinea'),
	('291', 'Eritrea'),
	('372', 'Estonia'),
	('268', 'Eswatini'),
	('251', 'Ethiopia'),
	('500', 'Falkland Islan'),
	('298', 'Faroe Islands'),
	('679', 'Fiji'),
	('358', 'Finland'),
	('33', 'France'),
	('594', 'French Guiana'),
	('689', 'French Polynesia'),
	('241', 'Gabon'),
	('220', 'Gambia'),
	('995', 'Georgia'),
	('49', 'Germany'),
	('233', 'Ghana'),
	('350', 'Gibraltar'),
	('30', 'Greece'),
	('299', 'Greenland'),
	('1', 'Grenada'),
	('590', 'Guadeloupe'),
	('1', 'Guam'),
	('502', 'Guatemala'),
	('224', 'Guinea'),
	('245', 'Guinea-Bissau'),
	('592', 'Guyana'),
	('509', 'Haiti'),
	('504', 'Honduras'),
	('852', 'Hong Kong SAR China'),
	('36', 'Hungary'),
	('354', 'Iceland'),
	('91', 'India'),
	('62', 'Indonesia'),
	('870', 'Inmarsat'),
	('98', 'Iran'),
	('964', 'Iraq'),
	('353', 'Ireland'),
	('881', 'Iridium'),
	('44', 'Isle of Man'),
	('972', 'Israel'),
	('39', 'Italy'),
	('1', 'Jamaica'),
	('81', 'Japan'),
	('44', 'Jersey'),
	('962', 'Jordan'),
	('7', 'Kazakhstan'),
	('254', 'Kenya'),
	('686', 'Kiribati'),
	('386', 'Kosovo'),
	('965', 'Kuwait'),
	('996', 'Kyrgyzstan'),
	('856', 'Laos'),
	('371', 'Latvia'),
	('961', 'Lebanon'),
	('266', 'Lesotho'),
	('231', 'Liberia'),
	('218', 'Libya'),
	('423', 'Liechtenstein'),
	('370', 'Lithuania'),
	('352', 'Luxembourg'),
	('853', 'Macao SAR China'),
	('261', 'Madagascar'),
	('265', 'Malawi'),
	('60', 'Malaysia'),
	('960', 'Maldives'),
	('223', 'Mali'),
	('356', 'Malta'),
	('596', 'Martinique'),
	('222', 'Mauritania'),
	('230', 'Mauritius'),
	('262', 'Mayotte'),
	('52', 'Mexico'),
	('691', 'Micronesia'),
	('373', 'Moldova'),
	('377', 'Monaco'),
	('976', 'Mongolia'),
	('382', 'Montenegro'),
	('1', 'Montserrat'),
	('212', 'Morocco'),
	('258', 'Mozambique'),
	('95', 'Myanmar (Burma)'),
	('264', 'Namibia'),
	('674', 'Nauru'),
	('977', 'Nepal'),
	('31', 'Netherlands'),
	('687', 'New Caledonia'),
	('64', 'New Zealand'),
	('505', 'Nicaragua'),
	('227', 'Niger'),
	('234', 'Nigeria'),
	('672', 'Norfolk Island'),
	('389', 'North Macedonia'),
	('1', 'Northern Mariana Islands'),
	('47', 'Norway'),
	('968', 'Oman'),
	('92', 'Pakistan'),
	('970', 'Palestinian Territories'),
	('507', 'Panama'),
	('675', 'Papua New Guinea'),
	('595', 'Paraguay'),
	('51', 'Peru'),
	('63', 'Philippines'),
	('48', 'Poland'),
	('351', 'Portugal'),
	('1', 'Puerto Rico'),
	('974', 'Qatar'),
	('40', 'Romania'),
	('7', 'Russia'),
	('250', 'Rwanda'),
	('262', 'Réunion'),
	('685', 'Samoa'),
	('378', 'San Marino'),
	('966', 'Saudi Arabia'),
	('221', 'Senegal'),
	('381', 'Serbia'),
	('248', 'Seychelles'),
	('232', 'Sierra Leone'),
	('65', 'Singapore'),
	('1', 'Sint Maarten'),
	('421', 'Slovakia'),
	('386', 'Slovenia'),
	('677', 'Solomon Islands'),
	('252', 'Somalia'),
	('27', 'South Africa'),
	('82', 'South Korea'),
	('211', 'South Sudan'),
	('34', 'Spain'),
	('94', 'Sri Lanka'),
	('1', 'St. Kitts & Nevis'),
	('1', 'St. Lucia'),
	('590', 'St. Martin'),
	('1', 'St. Vincent & Grenadines'),
	('597', 'Suriname'),
	('46', 'Sweden'),
	('41', 'Switzerland'),
	('239', 'São Tomé & Príncipe'),
	('886', 'Taiwan'),
	('992', 'Tajikistan'),
	('255', 'Tanzania'),
	('66', 'Thailand'),
	('882', 'Thuraya'),
	('670', 'Timor-Leste'),
	('228', 'Togo'),
	('676', 'Tonga'),
	('1', 'Trinida'),
	('216', 'Tunisia'),
	('90', 'Turkey'),
	('993', 'Turkmenistan'),
	('1', 'Turks & Caicos Islands'),
	('688', 'Tuvalu'),
	('1', 'U.S. Virgin Islands'),
	('256', 'Uganda'),
	('380', 'Ukraine'),
	('971', 'United Arab Emirates'),
	('44', 'United King'),
	('1', 'United States'),
	('598', 'Uruguay'),
	('998', 'Uzbekistan'),
	('678', 'Vanuatu'),
	('58', 'Venezuela'),
	('84', 'Vietnam'),
	('967', 'Yemen'),
	('260', 'Zambia'),
	('263', 'Zimbabwe'),
)




COUNTRY_CHOICES = (
	('af', 'Afghanistan'),
	('ax', 'Åland Islands'),
	('al', 'Albania'),
	('dz', 'Algeria'),
	('as', 'American Samoa'),
	('ad', 'Andorra'),
	('ao', 'Angola'),
	('ai', 'Anguilla'),
	('aq', 'Antarctica'),
	('ag', 'Antigua & Barbuda'),
	('ar', 'Argentina'),
	('am', 'Armenia'),
	('aw', 'Aruba'),
	('au', 'Australia'),
	('at', 'Austria'),
	('az', 'Azerbaijan'),
	('bs', 'Bahamas'),
	('bh', 'Bahrain'),
	('bd', 'Bangladesh'),
	('bb', 'Barbados'),
	('by', 'Belarus'),
	('be', 'Belgium'),
	('bz', 'Belize'),
	('bj', 'Benin'),
	('bm', 'Bermuda'),
	('bt', 'Bhutan'),
	('bo', 'Bolivia'),
	('ba', 'Bosnia & Herzegovina'),
	('bw', 'Botswana'),
	('bv', 'Bouvet Island'),
	('br', 'Brazil'),
	('io', 'British Indian Ocean Territory'),
	('bn', 'Brunei'),
	('bg', 'Bulgaria'),
	('bf', 'Burkina Faso'),
	('bi', 'Burundi'),
	('kh', 'Cambodia'),
	('cm', 'Cameroon'),
	('ca', 'Canada'),
	('cv', 'Cape Verde'),
	('bq', 'Caribbean Netherlands'),
	('ky', 'Cayman Islands'),
	('cf', 'Central African Republic'),
	('td', 'Chad'),
	('cl', 'Chile'),
	('cx', 'Christmas Island'),
	('cc', 'Cocos (Keeling) Islands'),
	('co', 'Colombia'),
	('km', 'Comoros'),
	('cg', 'Congo - Brazzaville'),
	('cd', 'Congo - Kinshasa'),
	('ck', 'Cook Islands'),
	('cr', 'Costa Rica'),
	('ci', 'Côte d’Ivoire'),
	('hr', 'Croatia'),
	('cu', 'Cuba'),
	('cw', 'Curaçao'),
	('cy', 'Cyprus'),
	('cz', 'Czechia'),
	('dk', 'Denmark'),
	('dj', 'Djibouti'),
	('dm', 'Dominica'),
	('do', 'Dominican Republic'),
	('ec', 'Ecuador'),
	('eg', 'Egypt'),
	('sv', 'El Salvador'),
	('gq', 'Equatorial Guinea'),
	('er', 'Eritrea'),
	('ee', 'Estonia'),
	('sz', 'Eswatini'),
	('et', 'Ethiopia'),
	('fk', 'Falkland Islands'),
	('fo', 'Faroe Islands'),
	('fj', 'Fiji'),
	('fi', 'Finland'),
	('fr', 'France'),
	('gf', 'French Guiana'),
	('pf', 'French Polynesia'),
	('tf', 'French Southern Territories'),
	('ga', 'Gabon'),
	('gm', 'Gambia'),
	('ge', 'Georgia'),
	('de', 'Germany'),
	('gh', 'Ghana'),
	('gi', 'Gibraltar'),
	('gr', 'Greece'),
	('gl', 'Greenland'),
	('gd', 'Grenada'),
	('gp', 'Guadeloupe'),
	('gu', 'Guam'),
	('gt', 'Guatemala'),
	('gg', 'Guernsey'),
	('gn', 'Guinea'),
	('gw', 'Guinea-Bissau'),
	('gy', 'Guyana'),
	('ht', 'Haiti'),
	('hn', 'Honduras'),
	('hk', 'Hong Kong SAR China'),
	('hu', 'Hungary'),
	('is', 'Iceland'),
	('in', 'India'),
	('id', 'Indonesia'),
	('ir', 'Iran'),
	('iq', 'Iraq'),
	('ie', 'Ireland'),
	('im', 'Isle of Man'),
	('il', 'Israel'),
	('it', 'Italy'),
	('jm', 'Jamaica'),
	('jp', 'Japan'),
	('je', 'Jersey'),
	('jo', 'Jordan'),
	('kz', 'Kazakhstan'),
	('ke', 'Kenya'),
	('ki', 'Kiribati'),
	('xk', 'Kosovo'),
	('kw', 'Kuwait'),
	('kg', 'Kyrgyzstan'),
	('la', 'Laos'),
	('lv', 'Latvia'),
	('lb', 'Lebanon'),
	('ls', 'Lesotho'),
	('lr', 'Liberia'),
	('ly', 'Libya'),
	('li', 'Liechtenstein'),
	('lt', 'Lithuania'),
	('lu', 'Luxembourg'),
	('mo', 'Macao SAR China'),
	('mg', 'Madagascar'),
	('mw', 'Malawi'),
	('my', 'Malaysia'),
	('mv', 'Maldives'),
	('ml', 'Mali'),
	('mt', 'Malta'),
	('mh', 'Marshall Islands'),
	('mq', 'Martinique'),
	('mr', 'Mauritania'),
	('mu', 'Mauritius'),
	('yt', 'Mayotte'),
	('mx', 'Mexico'),
	('fm', 'Micronesia'),
	('md', 'Moldova'),
	('mc', 'Monaco'),
	('mn', 'Mongolia'),
	('me', 'Montenegro'),
	('ms', 'Montserrat'),
	('ma', 'Morocco'),
	('mz', 'Mozambique'),
	('na', 'Namibia'),
	('nr', 'Nauru'),
	('np', 'Nepal'),
	('nl', 'Netherlands'),
	('nc', 'New Caledonia'),
	('nz', 'New Zealand'),
	('ni', 'Nicaragua'),
	('ne', 'Niger'),
	('ng', 'Nigeria'),
	('nu', 'Niue'),
	('nf', 'Norfolk Island'),
	('mk', 'North Macedonia'),
	('mp', 'Northern Mariana Islands'),
	('no', 'Norway'),
	('om', 'Oman'),
	('pk', 'Pakistan'),
	('pw', 'Palau'),
	('ps', 'Palestinian Territories'),
	('pa', 'Panama'),
	('pg', 'Papua New Guinea'),
	('py', 'Paraguay'),
	('pe', 'Peru'),
	('ph', 'Philippines'),
	('pn', 'Pitcairn Islands'),
	('pl', 'Poland'),
	('pt', 'Portugal'),
	('pr', 'Puerto Rico'),
	('qa', 'Qatar'),
	('re', 'Réunion'),
	('ro', 'Romania'),
	('ru', 'Russia'),
	('rw', 'Rwanda'),
	('ws', 'Samoa'),
	('sm', 'San Marino'),
	('st', 'São Tomé & Príncipe'),
	('sa', 'Saudi Arabia'),
	('sn', 'Senegal'),
	('rs', 'Serbia'),
	('sc', 'Seychelles'),
	('sl', 'Sierra Leone'),
	('sg', 'Singapore'),
	('sx', 'Sint Maarten'),
	('sk', 'Slovakia'),
	('si', 'Slovenia'),
	('sb', 'Solomon Islands'),
	('so', 'Somalia'),
	('za', 'South Africa'),
	('gs', 'South Georgia & South Sandwich Islands'),
	('kr', 'South Korea'),
	('es', 'Spain'),
	('lk', 'Sri Lanka'),
	('bl', 'St. Barthélemy'),
	('sh', 'St. Helena'),
	('kn', 'St. Kitts & Nevis'),
	('lc', 'St. Lucia'),
	('mf', 'St. Martin'),
	('pm', 'St. Pierre & Miquelon'),
	('vc', 'St. Vincent & Grenadines'),
	('sr', 'Suriname'),
	('se', 'Sweden'),
	('ch', 'Switzerland'),
	('tw', 'Taiwan'),
	('tj', 'Tajikistan'),
	('tz', 'Tanzania'),
	('th', 'Thailand'),
	('tl', 'Timor-Leste'),
	('tg', 'Togo'),
	('tk', 'Tokelau'),
	('to', 'Tonga'),
	('tt', 'Trinidad & Tobago'),
	('tn', 'Tunisia'),
	('tr', 'Turkey'),
	('tm', 'Turkmenistan'),
	('tc', 'Turks & Caicos Islands'),
	('tv', 'Tuvalu'),
	('vi', 'U.S. Virgin Islands'),
	('ug', 'Uganda'),
	('ua', 'Ukraine'),
	('ae', 'United Arab Emirates'),
	('gb', 'United Kingdom'),
	('us', 'United States'),
	('uy', 'Uruguay'),
	('uz', 'Uzbekistan'),
	('vu', 'Vanuatu'),
	('va', 'Vatican City'),
	('ve', 'Venezuela'),
	('vn', 'Vietnam'),
	('wf', 'Wallis & Futuna'),
	('ye', 'Yemen'),
	('zm', 'Zambia'),
	('zw', 'Zimbabwe'),
)




US_STATE_CHOICES = (
	('AL', 'Alabama'),
	('AK', 'Alaska'),
	('AZ', 'Arizona'),
	('AR', 'Arkansas'),
	('CA', 'California'),
	('CO', 'Colorado'),
	('CT', 'Connecticut'),
	('DE', 'Delaware'),
	('FL', 'Florida'),
	('GA', 'Georgia'),
	('HI', 'Hawaii'),
	('ID', 'Idaho'),
	('IL', 'Illinois'),
	('IN', 'Indiana'),
	('IA', 'Iowa'),
	('KS', 'Kansas'),
	('KY', 'Kentucky'),
	('LA', 'Louisiana'),
	('ME', 'Maine'),
	('MD', 'Maryland'),
	('MA', 'Massachusetts'),
	('MI', 'Michigan'),
	('MN', 'Minnesota'),
	('MS', 'Mississippi'),
	('MO', 'Missouri'),
	('MT', 'Montana'),
	('NE', 'Nebraska'),
	('NV', 'Nevada'),
	('NH', 'New Hampshire'),
	('NJ', 'New Jersey'),
	('NM', 'New Mexico'),
	('NY', 'New York'),
	('NC', 'North Carolina'),
	('ND', 'North Dakota'),
	('OH', 'Ohio'),
	('OK', 'Oklahoma'),
	('OR', 'Oregon'),
	('PA', 'Pennsylvania'),
	('RI', 'Rhode Island'),
	('SC', 'South Carolina'),
	('SD', 'South Dakota'),
	('TN', 'Tennessee'),
	('TX', 'Texas'),
	('UT', 'Utah'),
	('VT', 'Vermont'),
	('VA', 'Virginia'),
	('WA', 'Washington'),
	('WV', 'West Virginia'),
	('WI', 'Wisconsin'),
	('WY', 'Wyoming'),
	('AS', 'American Samoa'),
	('DC', 'District of Columbia'),
	('FM', 'Federated States of Micronesia'),
	('GU', 'Guam'),
	('MH', 'Marshall Islands'),
	('MP', 'Northern Mariana Islands'),
	('PW', 'Palau'),
	('PR', 'Puerto Rico'),
	('VI', 'Virgin Islands'),
)


