# Generated by Django 2.2.6 on 2020-01-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomsbrocode',
            name='is_michael_hatheway',
            field=models.BooleanField(default=False),
        ),
    ]
